In [6]:
import numpy as np 

# Basic  array creation

In [7]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

### array of numpy is fast then list of python 
### we store value different type of value in list but instead of numpy array we store same type of data 

In [4]:
a=[1,2,3,'hello world']
print(a)

[1, 2, 3, 'hello world']


In [5]:
np.array(a)

array(['1', '2', '3', 'hello world'], dtype='<U11')

In [9]:
two_D_list=[[1,2,3], [1,2,3], [1,2,3]]
print(two_D_list)

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]


#### list of python no sport multidemension or matrix
### but numpy array sport matrix

In [10]:
np.array(two_D_list)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## Numpy Array Genration Function

### np.arange() function that are used make list which you want

In [14]:
aar1=np.arange(10)
print(aar1)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

## zeros() and Ones() are used to preallacate memory 

In [19]:
arr=np.zeros(3)
arr
arrr=np.zeros((3,5))
arrr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
arr=np.ones(5)
arr
arr2=np.ones((4,5))
arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linsapce() that use for equaly genrate space between values

In [25]:
np.linspace(1,5,3)

array([1., 3., 5.])

In [26]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

## Random Genration Function

### Random library that genrate some random number 
rand() are function of random library

In [27]:
np.random.rand(5)

array([0.27162974, 0.53496955, 0.04282214, 0.99021532, 0.41405409])

In [28]:
np.random.rand(10)

array([0.52259801, 0.8001699 , 0.37347034, 0.06402149, 0.91149466,
       0.04809254, 0.77072004, 0.31167996, 0.02925203, 0.41182122])

### standrization mean always number are lie between -3 to 3

In [29]:
np.random.randn(5)

array([-0.09333311,  0.75950878,  0.32843909, -0.21593762,  0.237925  ])

In [30]:
np.random.randint(6)

1

In [31]:
np.random.randint(10,20,10)

array([19, 18, 10, 13, 18, 12, 14, 18, 12, 17])

## Array attribute

In [34]:
arr=np.array([[1,2,3], [1,2,3],[1,2,3]])
arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [33]:
arr.shape

(3, 3)

In [35]:
arr.size

9

In [36]:
arr.dtype

dtype('int32')

## Array Method 

In [37]:
arr.min()

1

In [38]:
arr.max()


3

In [39]:
arr.sum()

18

In [40]:
np.sum(arr, axis=0)

array([3, 6, 9])

In [41]:
np.sum(arr, axis=1)

array([6, 6, 6])

In [42]:
arr.mean()

2.0

In [43]:
arr.std()

0.816496580927726

### argmax() function that use for large element show index number
std() use for standrad derivation 

In [44]:
arr.argmax()

2

In [45]:
arr.argmin()

0

## Reshaping and Resizing

In [47]:
array=np.arange(1,31)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [50]:
array=array.reshape(6,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [51]:
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# Array Indexing And Array Slicing

## Numpy indexing and Sliching of vectors

In [54]:
arr3=np.arange(1,11)
arr3


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr3[6]

7

In [56]:
arr3[9]

10

Slicing Which we slect the portion of list and delte or show

In [57]:
arr3[1:5]

array([2, 3, 4, 5])

In [58]:
arr3[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [59]:
arr3[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## indexing and slicing numpy array or metrix 

In [62]:
indexing=np.arange(1,31)
indexing=indexing.reshape(5,6)
indexing


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [63]:
indexing[0]

array([1, 2, 3, 4, 5, 6])

In [64]:
indexing[0,0]

1

In [66]:
indexing[4,5]

30

In [72]:
indexing[0:3, 1:4]

array([[ 2,  3,  4],
       [ 8,  9, 10],
       [14, 15, 16]])

In [79]:
indexing[2:6,4:6 ]

array([[17, 18],
       [23, 24],
       [29, 30]])

In [83]:
indexing[0:2, 0:3]

array([[1, 2, 3],
       [7, 8, 9]])

In [84]:
indexing[2:4, 3:5]

array([[16, 17],
       [22, 23]])

## Bolean Indexing

In [89]:
bool_arr=np.arange(11,21)
bool_arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [91]:
boolean_indexing=bool_arr%2==0
boolean_indexing

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [94]:
arr=bool_arr[boolean_indexing]
arr

array([12, 14, 16, 18, 20])

 ## Array Operation

### Arithmetic operation

In [95]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5])

In [96]:
arr1+arr2

array([ 2,  4,  6,  8, 10])

In [97]:
arr1-arr2

array([0, 0, 0, 0, 0])

In [98]:
arr1*arr2

array([ 1,  4,  9, 16, 25])

In [99]:
arr1**arr2

array([   1,    4,   27,  256, 3125])

In [100]:
arr1/arr2

array([1., 1., 1., 1., 1.])

In [101]:
arr1//arr2

array([1, 1, 1, 1, 1])

## BroadCast

In [103]:
l=[1,2,3,4]
arr=np.array(l)
arr+10

array([11, 12, 13, 14])

In [105]:
arr2=np.arange(1,31)
arr2=arr2.reshape(5,6)
arr2*5

array([[  5,  10,  15,  20,  25,  30],
       [ 35,  40,  45,  50,  55,  60],
       [ 65,  70,  75,  80,  85,  90],
       [ 95, 100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145, 150]])

## Deep And Shallo Copy
Shallo copy means when we slice in array and broadcast then no change in orignal array so this is called shallo copy
Deep copy means when we slice in list and broadcast then change the orginal array so is called deep copy

In [120]:
arr=np.arange(1,11)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
arr[0:6]

array([1, 2, 3, 4, 5, 6])

In [122]:
arr*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [123]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [129]:

l=arr

In [130]:
l[0:6]

array([1, 2, 3, 4, 5, 6])

In [134]:
l*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [135]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Metrix Operation

In [149]:
a1=np.array([[1,2,],[4,3,]])
a2=np.array([[1,2,3],[7,8,9]])

In [150]:
a1

array([[1, 2],
       [4, 3]])

In [151]:
a2

array([[1, 2, 3],
       [7, 8, 9]])

In [152]:
a1.T

array([[1, 4],
       [2, 3]])

In [153]:
np.dot(a1,a2)

array([[15, 18, 21],
       [25, 32, 39]])

In [154]:
a1@a2

array([[15, 18, 21],
       [25, 32, 39]])

## Array Manipulation

### Stack vstack() hstack() column_stack()

In [166]:
b2=np.array([1,2,3,4,])
b3=np.array([5,6,7,8])


In [167]:
np.hstack((b2,b3))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [168]:
np.column_stack((b2,b3))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [169]:
np.vstack((b2,b3))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Spliiting hsplit() vsplite()

In [186]:
c=np.arange(1,26)
c=c.reshape(5,5)
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [189]:
np.hsplit(c,1)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])]

In [192]:
np.vsplit(c,1)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])]